AWSTemplateFormatVersion: '2010-09-09'
Description: Website deploy pipeline stack

Parameters:
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    MinLength: 40
    MaxLength: 40
    AllowedPattern: '[a-z0-9]*'

Resources:

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: CodeBuildRole
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/ruby:2.3.1
        Type: LINUX_CONTAINER
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: []
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: WebsiteSource
              Configuration:
                Owner: symphoniacloud
                Repo: symphonia-website
                PollForSourceChanges: true
                Branch: master
                OAuthToken: !Ref GitHubOAuthToken
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: 1
                  Provider: CodeBuild
              InputArtifacts:
                - Name: WebsiteSource
              OutputArtifacts:
                - Name: WebsiteBuild
              Configuration:
                  ProjectName: !Ref CodeBuildProject
              RunOrder: 1

  CodePipelineEvents:
    Type: AWS::Events::Rule
    Properties:
      Targets:
        - Arn: !Ref CodePipelineEventsTopic
          Id: SendToSNS
      EventPattern: !Sub |
        {
          "source": [ "aws.codepipeline" ],
          "detail-type": [
            "CodePipeline Pipeline Execution State Change",
            "CodePipeline Action Execution State Change",
            "CodePipeline Stage Execution State Change"
            ],
          "detail": {
            "pipeline": [ "${CodePipeline}" ]
            }
        }

  CodePipelineEventsTopic:
    Type: AWS::SNS::Topic

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess #TODO: Reduce permissions

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess #TODO: Reduce permissions
